### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Jim999AGC** [mwiedemeyer/RaspiMusicBox#3]
--DE--

Moin Moin,

ich habe folgendes Problem, wie ich es auch drehe und wende, ich bekomme das Programm nicht in den Autostart. Zumindest nicht mit offenem Terminal, so das RFID-Cards eingelesen werden können.
Der Raspi startet mit der Grafischen Oberfläche und als PI eingeloggt. 

Meine Frage nun, wie ist der Autostart gedacht? Oder ist es sogar erforderlich in der Konsole zu booten?

Vielen Dank schon einmal für die Hilfe.
MfG Jim

--EN--
Good Day,

I have the following problem,  I don't get the program the autostart. At least not with open terminal, that the RFID cards can be readed.
The Raspi starts with the graphical interface and logs in as PI.

My question, how is the Autostart thought? Or is it better to boot in the console?

Thanks a lot for the help.
MfG Jim

**Comment by mwiedemeyer** [comment]
Ich verwende eine Raspbian version ohne Desktop. Über raspi-config ist ein automatischer login konfiguriert (in die konsole). Der Autostart ist so konfiguriert: [LINK](http://www.opentechguides.com/how-to/article/raspberry-pi/5/raspberry-pi-auto-start.html)
